name: test_IAMReX
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行一次
  push:
jobs:
  test-IAMReX:
    runs-on: ubuntu-latest
    steps:
      - name: Clone AMReX and AMReX-Hydro repositories
        run: |
          mkdir -p /home/runner/work/repositories
          cd /home/runner/work/repositories
          git clone https://github.com/AMReX-Codes/amrex.git
          git clone https://github.com/AMReX-Fluids/AMReX-Hydro.git

      - name: Check out repository
        uses: actions/checkout@v3
        # with:
        #   path: /home/runner/work/repositories/IAMReX
      - name: List and pwd
        run: |
          cd /home/runner/work/repositories/IAMReX
          ls 
      - name: Run IAMReX tests
        run: |
          python Test_IAMReX/test_IAMReX.py
      - name: Finished.
        run: |
          echo "Tests completed!"